# TCL File Generated by Component Editor 18.1
# Sun May 17 00:25:08 EEST 2026
# DO NOT MODIFY


# 
# acc "acc" v1.0
#  2026.05.17.00:25:08
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module acc
# 
set_module_property DESCRIPTION ""
set_module_property NAME acc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP System
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME acc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL accelerator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file acc.sv SYSTEM_VERILOG PATH acc.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk_clk clk Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 80
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 s1_address address Input 5
add_interface_port s1 s1_read read Input 1
add_interface_port s1 s1_readdata readdata Output 32
add_interface_port s1 s1_write write Input 1
add_interface_port s1 s1_writedata writedata Input 32
add_interface_port s1 s1_waitrequest waitrequest Output 1
add_interface_port s1 s1_byteenable byteenable Input 4
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point acc_master
# 
add_interface acc_master avalon start
set_interface_property acc_master addressUnits SYMBOLS
set_interface_property acc_master associatedClock clk
set_interface_property acc_master associatedReset reset
set_interface_property acc_master bitsPerSymbol 8
set_interface_property acc_master burstOnBurstBoundariesOnly false
set_interface_property acc_master burstcountUnits WORDS
set_interface_property acc_master doStreamReads false
set_interface_property acc_master doStreamWrites false
set_interface_property acc_master holdTime 0
set_interface_property acc_master linewrapBursts false
set_interface_property acc_master maximumPendingReadTransactions 0
set_interface_property acc_master maximumPendingWriteTransactions 0
set_interface_property acc_master readLatency 0
set_interface_property acc_master readWaitTime 1
set_interface_property acc_master setupTime 0
set_interface_property acc_master timingUnits Cycles
set_interface_property acc_master writeWaitTime 0
set_interface_property acc_master ENABLED true
set_interface_property acc_master EXPORT_OF ""
set_interface_property acc_master PORT_NAME_MAP ""
set_interface_property acc_master CMSIS_SVD_VARIABLES ""
set_interface_property acc_master SVD_ADDRESS_GROUP ""

add_interface_port acc_master acc_master_address address Output 32
add_interface_port acc_master acc_master_read read Output 1
add_interface_port acc_master acc_master_readdata readdata Input 32
add_interface_port acc_master acc_master_write write Output 1
add_interface_port acc_master acc_master_writedata writedata Output 32
add_interface_port acc_master acc_master_waitrequest waitrequest Input 1
add_interface_port acc_master acc_master_byteenable byteenable Output 4
add_interface_port acc_master acc_master_readdatavalid readdatavalid Input 1

