// basics.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module basics (
		input  wire       clk_clk,         //      clk.clk
		output wire [9:0] leds_export,     //     leds.export
		input  wire       reset_reset_n,   //    reset.reset_n
		output wire [6:0] sev_seg_export,  //  sev_seg.export
		input  wire [9:0] switches_export  // switches.export
	);

	wire  [31:0] acc_0_acc_master_readdata;                                 // mm_interconnect_0:acc_0_acc_master_readdata -> acc_0:acc_master_readdata
	wire         acc_0_acc_master_waitrequest;                              // mm_interconnect_0:acc_0_acc_master_waitrequest -> acc_0:acc_master_waitrequest
	wire  [31:0] acc_0_acc_master_address;                                  // acc_0:acc_master_address -> mm_interconnect_0:acc_0_acc_master_address
	wire         acc_0_acc_master_read;                                     // acc_0:acc_master_read -> mm_interconnect_0:acc_0_acc_master_read
	wire   [3:0] acc_0_acc_master_byteenable;                               // acc_0:acc_master_byteenable -> mm_interconnect_0:acc_0_acc_master_byteenable
	wire         acc_0_acc_master_readdatavalid;                            // mm_interconnect_0:acc_0_acc_master_readdatavalid -> acc_0:acc_master_readdatavalid
	wire         acc_0_acc_master_write;                                    // acc_0:acc_master_write -> mm_interconnect_0:acc_0_acc_master_write
	wire  [31:0] acc_0_acc_master_writedata;                                // acc_0:acc_master_writedata -> mm_interconnect_0:acc_0_acc_master_writedata
	wire  [31:0] nios2_cpu_data_master_readdata;                            // mm_interconnect_0:nios2_cpu_data_master_readdata -> nios2_cpu:d_readdata
	wire         nios2_cpu_data_master_waitrequest;                         // mm_interconnect_0:nios2_cpu_data_master_waitrequest -> nios2_cpu:d_waitrequest
	wire         nios2_cpu_data_master_debugaccess;                         // nios2_cpu:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:nios2_cpu_data_master_debugaccess
	wire  [16:0] nios2_cpu_data_master_address;                             // nios2_cpu:d_address -> mm_interconnect_0:nios2_cpu_data_master_address
	wire   [3:0] nios2_cpu_data_master_byteenable;                          // nios2_cpu:d_byteenable -> mm_interconnect_0:nios2_cpu_data_master_byteenable
	wire         nios2_cpu_data_master_read;                                // nios2_cpu:d_read -> mm_interconnect_0:nios2_cpu_data_master_read
	wire         nios2_cpu_data_master_write;                               // nios2_cpu:d_write -> mm_interconnect_0:nios2_cpu_data_master_write
	wire  [31:0] nios2_cpu_data_master_writedata;                           // nios2_cpu:d_writedata -> mm_interconnect_0:nios2_cpu_data_master_writedata
	wire  [31:0] nios2_cpu_instruction_master_readdata;                     // mm_interconnect_0:nios2_cpu_instruction_master_readdata -> nios2_cpu:i_readdata
	wire         nios2_cpu_instruction_master_waitrequest;                  // mm_interconnect_0:nios2_cpu_instruction_master_waitrequest -> nios2_cpu:i_waitrequest
	wire  [16:0] nios2_cpu_instruction_master_address;                      // nios2_cpu:i_address -> mm_interconnect_0:nios2_cpu_instruction_master_address
	wire         nios2_cpu_instruction_master_read;                         // nios2_cpu:i_read -> mm_interconnect_0:nios2_cpu_instruction_master_read
	wire         mm_interconnect_0_b3_s1_chipselect;                        // mm_interconnect_0:b3_s1_chipselect -> b3:chipselect
	wire  [15:0] mm_interconnect_0_b3_s1_readdata;                          // b3:readdata -> mm_interconnect_0:b3_s1_readdata
	wire   [3:0] mm_interconnect_0_b3_s1_address;                           // mm_interconnect_0:b3_s1_address -> b3:address
	wire   [1:0] mm_interconnect_0_b3_s1_byteenable;                        // mm_interconnect_0:b3_s1_byteenable -> b3:byteenable
	wire         mm_interconnect_0_b3_s1_write;                             // mm_interconnect_0:b3_s1_write -> b3:write
	wire  [15:0] mm_interconnect_0_b3_s1_writedata;                         // mm_interconnect_0:b3_s1_writedata -> b3:writedata
	wire         mm_interconnect_0_b3_s1_clken;                             // mm_interconnect_0:b3_s1_clken -> b3:clken
	wire         mm_interconnect_0_w3_s1_chipselect;                        // mm_interconnect_0:w3_s1_chipselect -> w3:chipselect
	wire  [15:0] mm_interconnect_0_w3_s1_readdata;                          // w3:readdata -> mm_interconnect_0:w3_s1_readdata
	wire         mm_interconnect_0_w3_s1_debugaccess;                       // mm_interconnect_0:w3_s1_debugaccess -> w3:debugaccess
	wire   [7:0] mm_interconnect_0_w3_s1_address;                           // mm_interconnect_0:w3_s1_address -> w3:address
	wire   [1:0] mm_interconnect_0_w3_s1_byteenable;                        // mm_interconnect_0:w3_s1_byteenable -> w3:byteenable
	wire         mm_interconnect_0_w3_s1_write;                             // mm_interconnect_0:w3_s1_write -> w3:write
	wire  [15:0] mm_interconnect_0_w3_s1_writedata;                         // mm_interconnect_0:w3_s1_writedata -> w3:writedata
	wire         mm_interconnect_0_w3_s1_clken;                             // mm_interconnect_0:w3_s1_clken -> w3:clken
	wire         mm_interconnect_0_b2_s1_chipselect;                        // mm_interconnect_0:b2_s1_chipselect -> b2:chipselect
	wire  [15:0] mm_interconnect_0_b2_s1_readdata;                          // b2:readdata -> mm_interconnect_0:b2_s1_readdata
	wire   [3:0] mm_interconnect_0_b2_s1_address;                           // mm_interconnect_0:b2_s1_address -> b2:address
	wire   [1:0] mm_interconnect_0_b2_s1_byteenable;                        // mm_interconnect_0:b2_s1_byteenable -> b2:byteenable
	wire         mm_interconnect_0_b2_s1_write;                             // mm_interconnect_0:b2_s1_write -> b2:write
	wire  [15:0] mm_interconnect_0_b2_s1_writedata;                         // mm_interconnect_0:b2_s1_writedata -> b2:writedata
	wire         mm_interconnect_0_b2_s1_clken;                             // mm_interconnect_0:b2_s1_clken -> b2:clken
	wire         mm_interconnect_0_w2_s1_chipselect;                        // mm_interconnect_0:w2_s1_chipselect -> w2:chipselect
	wire  [15:0] mm_interconnect_0_w2_s1_readdata;                          // w2:readdata -> mm_interconnect_0:w2_s1_readdata
	wire         mm_interconnect_0_w2_s1_debugaccess;                       // mm_interconnect_0:w2_s1_debugaccess -> w2:debugaccess
	wire   [7:0] mm_interconnect_0_w2_s1_address;                           // mm_interconnect_0:w2_s1_address -> w2:address
	wire   [1:0] mm_interconnect_0_w2_s1_byteenable;                        // mm_interconnect_0:w2_s1_byteenable -> w2:byteenable
	wire         mm_interconnect_0_w2_s1_write;                             // mm_interconnect_0:w2_s1_write -> w2:write
	wire  [15:0] mm_interconnect_0_w2_s1_writedata;                         // mm_interconnect_0:w2_s1_writedata -> w2:writedata
	wire         mm_interconnect_0_w2_s1_clken;                             // mm_interconnect_0:w2_s1_clken -> w2:clken
	wire         mm_interconnect_0_b1_s1_chipselect;                        // mm_interconnect_0:b1_s1_chipselect -> b1:chipselect
	wire  [15:0] mm_interconnect_0_b1_s1_readdata;                          // b1:readdata -> mm_interconnect_0:b1_s1_readdata
	wire   [3:0] mm_interconnect_0_b1_s1_address;                           // mm_interconnect_0:b1_s1_address -> b1:address
	wire   [1:0] mm_interconnect_0_b1_s1_byteenable;                        // mm_interconnect_0:b1_s1_byteenable -> b1:byteenable
	wire         mm_interconnect_0_b1_s1_write;                             // mm_interconnect_0:b1_s1_write -> b1:write
	wire  [15:0] mm_interconnect_0_b1_s1_writedata;                         // mm_interconnect_0:b1_s1_writedata -> b1:writedata
	wire         mm_interconnect_0_b1_s1_clken;                             // mm_interconnect_0:b1_s1_clken -> b1:clken
	wire         mm_interconnect_0_w1_s1_chipselect;                        // mm_interconnect_0:w1_s1_chipselect -> w1:chipselect
	wire  [15:0] mm_interconnect_0_w1_s1_readdata;                          // w1:readdata -> mm_interconnect_0:w1_s1_readdata
	wire         mm_interconnect_0_w1_s1_debugaccess;                       // mm_interconnect_0:w1_s1_debugaccess -> w1:debugaccess
	wire  [13:0] mm_interconnect_0_w1_s1_address;                           // mm_interconnect_0:w1_s1_address -> w1:address
	wire   [1:0] mm_interconnect_0_w1_s1_byteenable;                        // mm_interconnect_0:w1_s1_byteenable -> w1:byteenable
	wire         mm_interconnect_0_w1_s1_write;                             // mm_interconnect_0:w1_s1_write -> w1:write
	wire  [15:0] mm_interconnect_0_w1_s1_writedata;                         // mm_interconnect_0:w1_s1_writedata -> w1:writedata
	wire         mm_interconnect_0_w1_s1_clken;                             // mm_interconnect_0:w1_s1_clken -> w1:clken
	wire         mm_interconnect_0_input_layer_s1_chipselect;               // mm_interconnect_0:input_layer_s1_chipselect -> input_layer:chipselect
	wire  [15:0] mm_interconnect_0_input_layer_s1_readdata;                 // input_layer:readdata -> mm_interconnect_0:input_layer_s1_readdata
	wire         mm_interconnect_0_input_layer_s1_debugaccess;              // mm_interconnect_0:input_layer_s1_debugaccess -> input_layer:debugaccess
	wire   [9:0] mm_interconnect_0_input_layer_s1_address;                  // mm_interconnect_0:input_layer_s1_address -> input_layer:address
	wire   [1:0] mm_interconnect_0_input_layer_s1_byteenable;               // mm_interconnect_0:input_layer_s1_byteenable -> input_layer:byteenable
	wire         mm_interconnect_0_input_layer_s1_write;                    // mm_interconnect_0:input_layer_s1_write -> input_layer:write
	wire  [15:0] mm_interconnect_0_input_layer_s1_writedata;                // mm_interconnect_0:input_layer_s1_writedata -> input_layer:writedata
	wire         mm_interconnect_0_input_layer_s1_clken;                    // mm_interconnect_0:input_layer_s1_clken -> input_layer:clken
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:jtag_uart_avalon_jtag_slave_chipselect -> jtag_uart:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;    // jtag_uart:av_readdata -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest; // jtag_uart:av_waitrequest -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;     // mm_interconnect_0:jtag_uart_avalon_jtag_slave_address -> jtag_uart:av_address
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;        // mm_interconnect_0:jtag_uart_avalon_jtag_slave_read -> jtag_uart:av_read_n
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;       // mm_interconnect_0:jtag_uart_avalon_jtag_slave_write -> jtag_uart:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;   // mm_interconnect_0:jtag_uart_avalon_jtag_slave_writedata -> jtag_uart:av_writedata
	wire  [31:0] mm_interconnect_0_sysid_qsys_0_control_slave_readdata;     // sysid_qsys_0:readdata -> mm_interconnect_0:sysid_qsys_0_control_slave_readdata
	wire   [0:0] mm_interconnect_0_sysid_qsys_0_control_slave_address;      // mm_interconnect_0:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	wire  [31:0] mm_interconnect_0_nios2_cpu_debug_mem_slave_readdata;      // nios2_cpu:debug_mem_slave_readdata -> mm_interconnect_0:nios2_cpu_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios2_cpu_debug_mem_slave_waitrequest;   // nios2_cpu:debug_mem_slave_waitrequest -> mm_interconnect_0:nios2_cpu_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios2_cpu_debug_mem_slave_debugaccess;   // mm_interconnect_0:nios2_cpu_debug_mem_slave_debugaccess -> nios2_cpu:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios2_cpu_debug_mem_slave_address;       // mm_interconnect_0:nios2_cpu_debug_mem_slave_address -> nios2_cpu:debug_mem_slave_address
	wire         mm_interconnect_0_nios2_cpu_debug_mem_slave_read;          // mm_interconnect_0:nios2_cpu_debug_mem_slave_read -> nios2_cpu:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios2_cpu_debug_mem_slave_byteenable;    // mm_interconnect_0:nios2_cpu_debug_mem_slave_byteenable -> nios2_cpu:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios2_cpu_debug_mem_slave_write;         // mm_interconnect_0:nios2_cpu_debug_mem_slave_write -> nios2_cpu:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios2_cpu_debug_mem_slave_writedata;     // mm_interconnect_0:nios2_cpu_debug_mem_slave_writedata -> nios2_cpu:debug_mem_slave_writedata
	wire         mm_interconnect_0_onchip_memory_s1_chipselect;             // mm_interconnect_0:onchip_memory_s1_chipselect -> onchip_memory:chipselect
	wire  [31:0] mm_interconnect_0_onchip_memory_s1_readdata;               // onchip_memory:readdata -> mm_interconnect_0:onchip_memory_s1_readdata
	wire  [13:0] mm_interconnect_0_onchip_memory_s1_address;                // mm_interconnect_0:onchip_memory_s1_address -> onchip_memory:address
	wire   [3:0] mm_interconnect_0_onchip_memory_s1_byteenable;             // mm_interconnect_0:onchip_memory_s1_byteenable -> onchip_memory:byteenable
	wire         mm_interconnect_0_onchip_memory_s1_write;                  // mm_interconnect_0:onchip_memory_s1_write -> onchip_memory:write
	wire  [31:0] mm_interconnect_0_onchip_memory_s1_writedata;              // mm_interconnect_0:onchip_memory_s1_writedata -> onchip_memory:writedata
	wire         mm_interconnect_0_onchip_memory_s1_clken;                  // mm_interconnect_0:onchip_memory_s1_clken -> onchip_memory:clken
	wire         mm_interconnect_0_leds_s1_chipselect;                      // mm_interconnect_0:leds_s1_chipselect -> leds:chipselect
	wire  [31:0] mm_interconnect_0_leds_s1_readdata;                        // leds:readdata -> mm_interconnect_0:leds_s1_readdata
	wire   [1:0] mm_interconnect_0_leds_s1_address;                         // mm_interconnect_0:leds_s1_address -> leds:address
	wire         mm_interconnect_0_leds_s1_write;                           // mm_interconnect_0:leds_s1_write -> leds:write_n
	wire  [31:0] mm_interconnect_0_leds_s1_writedata;                       // mm_interconnect_0:leds_s1_writedata -> leds:writedata
	wire  [31:0] mm_interconnect_0_switches_s1_readdata;                    // switches:readdata -> mm_interconnect_0:switches_s1_readdata
	wire   [1:0] mm_interconnect_0_switches_s1_address;                     // mm_interconnect_0:switches_s1_address -> switches:address
	wire         mm_interconnect_0_sev_seg_s1_chipselect;                   // mm_interconnect_0:sev_seg_s1_chipselect -> sev_seg:chipselect
	wire  [31:0] mm_interconnect_0_sev_seg_s1_readdata;                     // sev_seg:readdata -> mm_interconnect_0:sev_seg_s1_readdata
	wire   [1:0] mm_interconnect_0_sev_seg_s1_address;                      // mm_interconnect_0:sev_seg_s1_address -> sev_seg:address
	wire         mm_interconnect_0_sev_seg_s1_write;                        // mm_interconnect_0:sev_seg_s1_write -> sev_seg:write_n
	wire  [31:0] mm_interconnect_0_sev_seg_s1_writedata;                    // mm_interconnect_0:sev_seg_s1_writedata -> sev_seg:writedata
	wire  [31:0] mm_interconnect_0_acc_0_s1_readdata;                       // acc_0:s1_readdata -> mm_interconnect_0:acc_0_s1_readdata
	wire         mm_interconnect_0_acc_0_s1_waitrequest;                    // acc_0:s1_waitrequest -> mm_interconnect_0:acc_0_s1_waitrequest
	wire   [4:0] mm_interconnect_0_acc_0_s1_address;                        // mm_interconnect_0:acc_0_s1_address -> acc_0:s1_address
	wire         mm_interconnect_0_acc_0_s1_read;                           // mm_interconnect_0:acc_0_s1_read -> acc_0:s1_read
	wire   [3:0] mm_interconnect_0_acc_0_s1_byteenable;                     // mm_interconnect_0:acc_0_s1_byteenable -> acc_0:s1_byteenable
	wire         mm_interconnect_0_acc_0_s1_write;                          // mm_interconnect_0:acc_0_s1_write -> acc_0:s1_write
	wire  [31:0] mm_interconnect_0_acc_0_s1_writedata;                      // mm_interconnect_0:acc_0_s1_writedata -> acc_0:s1_writedata
	wire         irq_mapper_receiver0_irq;                                  // jtag_uart:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios2_cpu_irq_irq;                                         // irq_mapper:sender_irq -> nios2_cpu:irq
	wire         rst_controller_reset_out_reset;                            // rst_controller:reset_out -> [acc_0:reset_reset, b1:reset, b2:reset, b3:reset, input_layer:reset, irq_mapper:reset, jtag_uart:rst_n, leds:reset_n, mm_interconnect_0:acc_0_reset_reset_bridge_in_reset_reset, nios2_cpu:reset_n, onchip_memory:reset, rst_translator:in_reset, sev_seg:reset_n, switches:reset_n, w1:reset, w2:reset, w3:reset]
	wire         rst_controller_reset_out_reset_req;                        // rst_controller:reset_req -> [b1:reset_req, b2:reset_req, b3:reset_req, input_layer:reset_req, nios2_cpu:reset_req, onchip_memory:reset_req, rst_translator:reset_req_in, w1:reset_req, w2:reset_req, w3:reset_req]
	wire         nios2_cpu_debug_reset_request_reset;                       // nios2_cpu:debug_reset_request -> rst_controller:reset_in1
	wire         rst_controller_001_reset_out_reset;                        // rst_controller_001:reset_out -> [mm_interconnect_0:sysid_qsys_0_reset_reset_bridge_in_reset_reset, sysid_qsys_0:reset_n]

	acc acc_0 (
		.clk_clk                  (clk_clk),                                //        clk.clk
		.s1_address               (mm_interconnect_0_acc_0_s1_address),     //         s1.address
		.s1_read                  (mm_interconnect_0_acc_0_s1_read),        //           .read
		.s1_readdata              (mm_interconnect_0_acc_0_s1_readdata),    //           .readdata
		.s1_write                 (mm_interconnect_0_acc_0_s1_write),       //           .write
		.s1_writedata             (mm_interconnect_0_acc_0_s1_writedata),   //           .writedata
		.s1_waitrequest           (mm_interconnect_0_acc_0_s1_waitrequest), //           .waitrequest
		.s1_byteenable            (mm_interconnect_0_acc_0_s1_byteenable),  //           .byteenable
		.reset_reset              (rst_controller_reset_out_reset),         //      reset.reset
		.acc_master_address       (acc_0_acc_master_address),               // acc_master.address
		.acc_master_read          (acc_0_acc_master_read),                  //           .read
		.acc_master_readdata      (acc_0_acc_master_readdata),              //           .readdata
		.acc_master_write         (acc_0_acc_master_write),                 //           .write
		.acc_master_writedata     (acc_0_acc_master_writedata),             //           .writedata
		.acc_master_waitrequest   (acc_0_acc_master_waitrequest),           //           .waitrequest
		.acc_master_byteenable    (acc_0_acc_master_byteenable),            //           .byteenable
		.acc_master_readdatavalid (acc_0_acc_master_readdatavalid)          //           .readdatavalid
	);

	basics_b1 b1 (
		.clk        (clk_clk),                            //   clk1.clk
		.address    (mm_interconnect_0_b1_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_b1_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_b1_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_b1_s1_write),      //       .write
		.readdata   (mm_interconnect_0_b1_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_b1_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_b1_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),     // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req), //       .reset_req
		.freeze     (1'b0)                                // (terminated)
	);

	basics_b2 b2 (
		.clk        (clk_clk),                            //   clk1.clk
		.address    (mm_interconnect_0_b2_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_b2_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_b2_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_b2_s1_write),      //       .write
		.readdata   (mm_interconnect_0_b2_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_b2_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_b2_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),     // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req), //       .reset_req
		.freeze     (1'b0)                                // (terminated)
	);

	basics_b3 b3 (
		.clk        (clk_clk),                            //   clk1.clk
		.address    (mm_interconnect_0_b3_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_b3_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_b3_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_b3_s1_write),      //       .write
		.readdata   (mm_interconnect_0_b3_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_b3_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_b3_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),     // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req), //       .reset_req
		.freeze     (1'b0)                                // (terminated)
	);

	basics_input_layer input_layer (
		.clk         (clk_clk),                                      //   clk1.clk
		.address     (mm_interconnect_0_input_layer_s1_address),     //     s1.address
		.debugaccess (mm_interconnect_0_input_layer_s1_debugaccess), //       .debugaccess
		.clken       (mm_interconnect_0_input_layer_s1_clken),       //       .clken
		.chipselect  (mm_interconnect_0_input_layer_s1_chipselect),  //       .chipselect
		.write       (mm_interconnect_0_input_layer_s1_write),       //       .write
		.readdata    (mm_interconnect_0_input_layer_s1_readdata),    //       .readdata
		.writedata   (mm_interconnect_0_input_layer_s1_writedata),   //       .writedata
		.byteenable  (mm_interconnect_0_input_layer_s1_byteenable),  //       .byteenable
		.reset       (rst_controller_reset_out_reset),               // reset1.reset
		.reset_req   (rst_controller_reset_out_reset_req),           //       .reset_req
		.freeze      (1'b0)                                          // (terminated)
	);

	basics_jtag_uart jtag_uart (
		.clk            (clk_clk),                                                   //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                           //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                   //               irq.irq
	);

	basics_leds leds (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_leds_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_leds_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_leds_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_leds_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_leds_s1_readdata),   //                    .readdata
		.out_port   (leds_export)                           // external_connection.export
	);

	basics_nios2_cpu nios2_cpu (
		.clk                                 (clk_clk),                                                 //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                         //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                      //                          .reset_req
		.d_address                           (nios2_cpu_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios2_cpu_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios2_cpu_data_master_read),                              //                          .read
		.d_readdata                          (nios2_cpu_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios2_cpu_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios2_cpu_data_master_write),                             //                          .write
		.d_writedata                         (nios2_cpu_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (nios2_cpu_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios2_cpu_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios2_cpu_instruction_master_read),                       //                          .read
		.i_readdata                          (nios2_cpu_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios2_cpu_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (nios2_cpu_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios2_cpu_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios2_cpu_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios2_cpu_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios2_cpu_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios2_cpu_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios2_cpu_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios2_cpu_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios2_cpu_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios2_cpu_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                         // custom_instruction_master.readra
	);

	basics_onchip_memory onchip_memory (
		.clk        (clk_clk),                                       //   clk1.clk
		.address    (mm_interconnect_0_onchip_memory_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_memory_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_memory_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_memory_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_memory_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_memory_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_memory_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),            //       .reset_req
		.freeze     (1'b0)                                           // (terminated)
	);

	basics_sev_seg sev_seg (
		.clk        (clk_clk),                                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address    (mm_interconnect_0_sev_seg_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_sev_seg_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_sev_seg_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_sev_seg_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_sev_seg_s1_readdata),   //                    .readdata
		.out_port   (sev_seg_export)                           // external_connection.export
	);

	basics_switches switches (
		.clk      (clk_clk),                                //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address  (mm_interconnect_0_switches_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_switches_s1_readdata), //                    .readdata
		.in_port  (switches_export)                         // external_connection.export
	);

	basics_sysid_qsys_0 sysid_qsys_0 (
		.clock    (clk_clk),                                               //           clk.clk
		.reset_n  (~rst_controller_001_reset_out_reset),                   //         reset.reset_n
		.readdata (mm_interconnect_0_sysid_qsys_0_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sysid_qsys_0_control_slave_address)   //              .address
	);

	basics_w1 w1 (
		.clk         (clk_clk),                             //   clk1.clk
		.address     (mm_interconnect_0_w1_s1_address),     //     s1.address
		.debugaccess (mm_interconnect_0_w1_s1_debugaccess), //       .debugaccess
		.clken       (mm_interconnect_0_w1_s1_clken),       //       .clken
		.chipselect  (mm_interconnect_0_w1_s1_chipselect),  //       .chipselect
		.write       (mm_interconnect_0_w1_s1_write),       //       .write
		.readdata    (mm_interconnect_0_w1_s1_readdata),    //       .readdata
		.writedata   (mm_interconnect_0_w1_s1_writedata),   //       .writedata
		.byteenable  (mm_interconnect_0_w1_s1_byteenable),  //       .byteenable
		.reset       (rst_controller_reset_out_reset),      // reset1.reset
		.reset_req   (rst_controller_reset_out_reset_req),  //       .reset_req
		.freeze      (1'b0)                                 // (terminated)
	);

	basics_w2 w2 (
		.clk         (clk_clk),                             //   clk1.clk
		.address     (mm_interconnect_0_w2_s1_address),     //     s1.address
		.debugaccess (mm_interconnect_0_w2_s1_debugaccess), //       .debugaccess
		.clken       (mm_interconnect_0_w2_s1_clken),       //       .clken
		.chipselect  (mm_interconnect_0_w2_s1_chipselect),  //       .chipselect
		.write       (mm_interconnect_0_w2_s1_write),       //       .write
		.readdata    (mm_interconnect_0_w2_s1_readdata),    //       .readdata
		.writedata   (mm_interconnect_0_w2_s1_writedata),   //       .writedata
		.byteenable  (mm_interconnect_0_w2_s1_byteenable),  //       .byteenable
		.reset       (rst_controller_reset_out_reset),      // reset1.reset
		.reset_req   (rst_controller_reset_out_reset_req),  //       .reset_req
		.freeze      (1'b0)                                 // (terminated)
	);

	basics_w3 w3 (
		.clk         (clk_clk),                             //   clk1.clk
		.address     (mm_interconnect_0_w3_s1_address),     //     s1.address
		.debugaccess (mm_interconnect_0_w3_s1_debugaccess), //       .debugaccess
		.clken       (mm_interconnect_0_w3_s1_clken),       //       .clken
		.chipselect  (mm_interconnect_0_w3_s1_chipselect),  //       .chipselect
		.write       (mm_interconnect_0_w3_s1_write),       //       .write
		.readdata    (mm_interconnect_0_w3_s1_readdata),    //       .readdata
		.writedata   (mm_interconnect_0_w3_s1_writedata),   //       .writedata
		.byteenable  (mm_interconnect_0_w3_s1_byteenable),  //       .byteenable
		.reset       (rst_controller_reset_out_reset),      // reset1.reset
		.reset_req   (rst_controller_reset_out_reset_req),  //       .reset_req
		.freeze      (1'b0)                                 // (terminated)
	);

	basics_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                  (clk_clk),                                                   //                                clk_0_clk.clk
		.acc_0_reset_reset_bridge_in_reset_reset        (rst_controller_reset_out_reset),                            //        acc_0_reset_reset_bridge_in_reset.reset
		.sysid_qsys_0_reset_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                        // sysid_qsys_0_reset_reset_bridge_in_reset.reset
		.acc_0_acc_master_address                       (acc_0_acc_master_address),                                  //                         acc_0_acc_master.address
		.acc_0_acc_master_waitrequest                   (acc_0_acc_master_waitrequest),                              //                                         .waitrequest
		.acc_0_acc_master_byteenable                    (acc_0_acc_master_byteenable),                               //                                         .byteenable
		.acc_0_acc_master_read                          (acc_0_acc_master_read),                                     //                                         .read
		.acc_0_acc_master_readdata                      (acc_0_acc_master_readdata),                                 //                                         .readdata
		.acc_0_acc_master_readdatavalid                 (acc_0_acc_master_readdatavalid),                            //                                         .readdatavalid
		.acc_0_acc_master_write                         (acc_0_acc_master_write),                                    //                                         .write
		.acc_0_acc_master_writedata                     (acc_0_acc_master_writedata),                                //                                         .writedata
		.nios2_cpu_data_master_address                  (nios2_cpu_data_master_address),                             //                    nios2_cpu_data_master.address
		.nios2_cpu_data_master_waitrequest              (nios2_cpu_data_master_waitrequest),                         //                                         .waitrequest
		.nios2_cpu_data_master_byteenable               (nios2_cpu_data_master_byteenable),                          //                                         .byteenable
		.nios2_cpu_data_master_read                     (nios2_cpu_data_master_read),                                //                                         .read
		.nios2_cpu_data_master_readdata                 (nios2_cpu_data_master_readdata),                            //                                         .readdata
		.nios2_cpu_data_master_write                    (nios2_cpu_data_master_write),                               //                                         .write
		.nios2_cpu_data_master_writedata                (nios2_cpu_data_master_writedata),                           //                                         .writedata
		.nios2_cpu_data_master_debugaccess              (nios2_cpu_data_master_debugaccess),                         //                                         .debugaccess
		.nios2_cpu_instruction_master_address           (nios2_cpu_instruction_master_address),                      //             nios2_cpu_instruction_master.address
		.nios2_cpu_instruction_master_waitrequest       (nios2_cpu_instruction_master_waitrequest),                  //                                         .waitrequest
		.nios2_cpu_instruction_master_read              (nios2_cpu_instruction_master_read),                         //                                         .read
		.nios2_cpu_instruction_master_readdata          (nios2_cpu_instruction_master_readdata),                     //                                         .readdata
		.acc_0_s1_address                               (mm_interconnect_0_acc_0_s1_address),                        //                                 acc_0_s1.address
		.acc_0_s1_write                                 (mm_interconnect_0_acc_0_s1_write),                          //                                         .write
		.acc_0_s1_read                                  (mm_interconnect_0_acc_0_s1_read),                           //                                         .read
		.acc_0_s1_readdata                              (mm_interconnect_0_acc_0_s1_readdata),                       //                                         .readdata
		.acc_0_s1_writedata                             (mm_interconnect_0_acc_0_s1_writedata),                      //                                         .writedata
		.acc_0_s1_byteenable                            (mm_interconnect_0_acc_0_s1_byteenable),                     //                                         .byteenable
		.acc_0_s1_waitrequest                           (mm_interconnect_0_acc_0_s1_waitrequest),                    //                                         .waitrequest
		.b1_s1_address                                  (mm_interconnect_0_b1_s1_address),                           //                                    b1_s1.address
		.b1_s1_write                                    (mm_interconnect_0_b1_s1_write),                             //                                         .write
		.b1_s1_readdata                                 (mm_interconnect_0_b1_s1_readdata),                          //                                         .readdata
		.b1_s1_writedata                                (mm_interconnect_0_b1_s1_writedata),                         //                                         .writedata
		.b1_s1_byteenable                               (mm_interconnect_0_b1_s1_byteenable),                        //                                         .byteenable
		.b1_s1_chipselect                               (mm_interconnect_0_b1_s1_chipselect),                        //                                         .chipselect
		.b1_s1_clken                                    (mm_interconnect_0_b1_s1_clken),                             //                                         .clken
		.b2_s1_address                                  (mm_interconnect_0_b2_s1_address),                           //                                    b2_s1.address
		.b2_s1_write                                    (mm_interconnect_0_b2_s1_write),                             //                                         .write
		.b2_s1_readdata                                 (mm_interconnect_0_b2_s1_readdata),                          //                                         .readdata
		.b2_s1_writedata                                (mm_interconnect_0_b2_s1_writedata),                         //                                         .writedata
		.b2_s1_byteenable                               (mm_interconnect_0_b2_s1_byteenable),                        //                                         .byteenable
		.b2_s1_chipselect                               (mm_interconnect_0_b2_s1_chipselect),                        //                                         .chipselect
		.b2_s1_clken                                    (mm_interconnect_0_b2_s1_clken),                             //                                         .clken
		.b3_s1_address                                  (mm_interconnect_0_b3_s1_address),                           //                                    b3_s1.address
		.b3_s1_write                                    (mm_interconnect_0_b3_s1_write),                             //                                         .write
		.b3_s1_readdata                                 (mm_interconnect_0_b3_s1_readdata),                          //                                         .readdata
		.b3_s1_writedata                                (mm_interconnect_0_b3_s1_writedata),                         //                                         .writedata
		.b3_s1_byteenable                               (mm_interconnect_0_b3_s1_byteenable),                        //                                         .byteenable
		.b3_s1_chipselect                               (mm_interconnect_0_b3_s1_chipselect),                        //                                         .chipselect
		.b3_s1_clken                                    (mm_interconnect_0_b3_s1_clken),                             //                                         .clken
		.input_layer_s1_address                         (mm_interconnect_0_input_layer_s1_address),                  //                           input_layer_s1.address
		.input_layer_s1_write                           (mm_interconnect_0_input_layer_s1_write),                    //                                         .write
		.input_layer_s1_readdata                        (mm_interconnect_0_input_layer_s1_readdata),                 //                                         .readdata
		.input_layer_s1_writedata                       (mm_interconnect_0_input_layer_s1_writedata),                //                                         .writedata
		.input_layer_s1_byteenable                      (mm_interconnect_0_input_layer_s1_byteenable),               //                                         .byteenable
		.input_layer_s1_chipselect                      (mm_interconnect_0_input_layer_s1_chipselect),               //                                         .chipselect
		.input_layer_s1_clken                           (mm_interconnect_0_input_layer_s1_clken),                    //                                         .clken
		.input_layer_s1_debugaccess                     (mm_interconnect_0_input_layer_s1_debugaccess),              //                                         .debugaccess
		.jtag_uart_avalon_jtag_slave_address            (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //              jtag_uart_avalon_jtag_slave.address
		.jtag_uart_avalon_jtag_slave_write              (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),       //                                         .write
		.jtag_uart_avalon_jtag_slave_read               (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),        //                                         .read
		.jtag_uart_avalon_jtag_slave_readdata           (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                                         .readdata
		.jtag_uart_avalon_jtag_slave_writedata          (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                                         .writedata
		.jtag_uart_avalon_jtag_slave_waitrequest        (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                                         .waitrequest
		.jtag_uart_avalon_jtag_slave_chipselect         (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  //                                         .chipselect
		.leds_s1_address                                (mm_interconnect_0_leds_s1_address),                         //                                  leds_s1.address
		.leds_s1_write                                  (mm_interconnect_0_leds_s1_write),                           //                                         .write
		.leds_s1_readdata                               (mm_interconnect_0_leds_s1_readdata),                        //                                         .readdata
		.leds_s1_writedata                              (mm_interconnect_0_leds_s1_writedata),                       //                                         .writedata
		.leds_s1_chipselect                             (mm_interconnect_0_leds_s1_chipselect),                      //                                         .chipselect
		.nios2_cpu_debug_mem_slave_address              (mm_interconnect_0_nios2_cpu_debug_mem_slave_address),       //                nios2_cpu_debug_mem_slave.address
		.nios2_cpu_debug_mem_slave_write                (mm_interconnect_0_nios2_cpu_debug_mem_slave_write),         //                                         .write
		.nios2_cpu_debug_mem_slave_read                 (mm_interconnect_0_nios2_cpu_debug_mem_slave_read),          //                                         .read
		.nios2_cpu_debug_mem_slave_readdata             (mm_interconnect_0_nios2_cpu_debug_mem_slave_readdata),      //                                         .readdata
		.nios2_cpu_debug_mem_slave_writedata            (mm_interconnect_0_nios2_cpu_debug_mem_slave_writedata),     //                                         .writedata
		.nios2_cpu_debug_mem_slave_byteenable           (mm_interconnect_0_nios2_cpu_debug_mem_slave_byteenable),    //                                         .byteenable
		.nios2_cpu_debug_mem_slave_waitrequest          (mm_interconnect_0_nios2_cpu_debug_mem_slave_waitrequest),   //                                         .waitrequest
		.nios2_cpu_debug_mem_slave_debugaccess          (mm_interconnect_0_nios2_cpu_debug_mem_slave_debugaccess),   //                                         .debugaccess
		.onchip_memory_s1_address                       (mm_interconnect_0_onchip_memory_s1_address),                //                         onchip_memory_s1.address
		.onchip_memory_s1_write                         (mm_interconnect_0_onchip_memory_s1_write),                  //                                         .write
		.onchip_memory_s1_readdata                      (mm_interconnect_0_onchip_memory_s1_readdata),               //                                         .readdata
		.onchip_memory_s1_writedata                     (mm_interconnect_0_onchip_memory_s1_writedata),              //                                         .writedata
		.onchip_memory_s1_byteenable                    (mm_interconnect_0_onchip_memory_s1_byteenable),             //                                         .byteenable
		.onchip_memory_s1_chipselect                    (mm_interconnect_0_onchip_memory_s1_chipselect),             //                                         .chipselect
		.onchip_memory_s1_clken                         (mm_interconnect_0_onchip_memory_s1_clken),                  //                                         .clken
		.sev_seg_s1_address                             (mm_interconnect_0_sev_seg_s1_address),                      //                               sev_seg_s1.address
		.sev_seg_s1_write                               (mm_interconnect_0_sev_seg_s1_write),                        //                                         .write
		.sev_seg_s1_readdata                            (mm_interconnect_0_sev_seg_s1_readdata),                     //                                         .readdata
		.sev_seg_s1_writedata                           (mm_interconnect_0_sev_seg_s1_writedata),                    //                                         .writedata
		.sev_seg_s1_chipselect                          (mm_interconnect_0_sev_seg_s1_chipselect),                   //                                         .chipselect
		.switches_s1_address                            (mm_interconnect_0_switches_s1_address),                     //                              switches_s1.address
		.switches_s1_readdata                           (mm_interconnect_0_switches_s1_readdata),                    //                                         .readdata
		.sysid_qsys_0_control_slave_address             (mm_interconnect_0_sysid_qsys_0_control_slave_address),      //               sysid_qsys_0_control_slave.address
		.sysid_qsys_0_control_slave_readdata            (mm_interconnect_0_sysid_qsys_0_control_slave_readdata),     //                                         .readdata
		.w1_s1_address                                  (mm_interconnect_0_w1_s1_address),                           //                                    w1_s1.address
		.w1_s1_write                                    (mm_interconnect_0_w1_s1_write),                             //                                         .write
		.w1_s1_readdata                                 (mm_interconnect_0_w1_s1_readdata),                          //                                         .readdata
		.w1_s1_writedata                                (mm_interconnect_0_w1_s1_writedata),                         //                                         .writedata
		.w1_s1_byteenable                               (mm_interconnect_0_w1_s1_byteenable),                        //                                         .byteenable
		.w1_s1_chipselect                               (mm_interconnect_0_w1_s1_chipselect),                        //                                         .chipselect
		.w1_s1_clken                                    (mm_interconnect_0_w1_s1_clken),                             //                                         .clken
		.w1_s1_debugaccess                              (mm_interconnect_0_w1_s1_debugaccess),                       //                                         .debugaccess
		.w2_s1_address                                  (mm_interconnect_0_w2_s1_address),                           //                                    w2_s1.address
		.w2_s1_write                                    (mm_interconnect_0_w2_s1_write),                             //                                         .write
		.w2_s1_readdata                                 (mm_interconnect_0_w2_s1_readdata),                          //                                         .readdata
		.w2_s1_writedata                                (mm_interconnect_0_w2_s1_writedata),                         //                                         .writedata
		.w2_s1_byteenable                               (mm_interconnect_0_w2_s1_byteenable),                        //                                         .byteenable
		.w2_s1_chipselect                               (mm_interconnect_0_w2_s1_chipselect),                        //                                         .chipselect
		.w2_s1_clken                                    (mm_interconnect_0_w2_s1_clken),                             //                                         .clken
		.w2_s1_debugaccess                              (mm_interconnect_0_w2_s1_debugaccess),                       //                                         .debugaccess
		.w3_s1_address                                  (mm_interconnect_0_w3_s1_address),                           //                                    w3_s1.address
		.w3_s1_write                                    (mm_interconnect_0_w3_s1_write),                             //                                         .write
		.w3_s1_readdata                                 (mm_interconnect_0_w3_s1_readdata),                          //                                         .readdata
		.w3_s1_writedata                                (mm_interconnect_0_w3_s1_writedata),                         //                                         .writedata
		.w3_s1_byteenable                               (mm_interconnect_0_w3_s1_byteenable),                        //                                         .byteenable
		.w3_s1_chipselect                               (mm_interconnect_0_w3_s1_chipselect),                        //                                         .chipselect
		.w3_s1_clken                                    (mm_interconnect_0_w3_s1_clken),                             //                                         .clken
		.w3_s1_debugaccess                              (mm_interconnect_0_w3_s1_debugaccess)                        //                                         .debugaccess
	);

	basics_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios2_cpu_irq_irq)               //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                      // reset_in0.reset
		.reset_in1      (nios2_cpu_debug_reset_request_reset), // reset_in1.reset
		.clk            (clk_clk),                             //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),      // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req),  //          .reset_req
		.reset_req_in0  (1'b0),                                // (terminated)
		.reset_req_in1  (1'b0),                                // (terminated)
		.reset_in2      (1'b0),                                // (terminated)
		.reset_req_in2  (1'b0),                                // (terminated)
		.reset_in3      (1'b0),                                // (terminated)
		.reset_req_in3  (1'b0),                                // (terminated)
		.reset_in4      (1'b0),                                // (terminated)
		.reset_req_in4  (1'b0),                                // (terminated)
		.reset_in5      (1'b0),                                // (terminated)
		.reset_req_in5  (1'b0),                                // (terminated)
		.reset_in6      (1'b0),                                // (terminated)
		.reset_req_in6  (1'b0),                                // (terminated)
		.reset_in7      (1'b0),                                // (terminated)
		.reset_req_in7  (1'b0),                                // (terminated)
		.reset_in8      (1'b0),                                // (terminated)
		.reset_req_in8  (1'b0),                                // (terminated)
		.reset_in9      (1'b0),                                // (terminated)
		.reset_req_in9  (1'b0),                                // (terminated)
		.reset_in10     (1'b0),                                // (terminated)
		.reset_req_in10 (1'b0),                                // (terminated)
		.reset_in11     (1'b0),                                // (terminated)
		.reset_req_in11 (1'b0),                                // (terminated)
		.reset_in12     (1'b0),                                // (terminated)
		.reset_req_in12 (1'b0),                                // (terminated)
		.reset_in13     (1'b0),                                // (terminated)
		.reset_req_in13 (1'b0),                                // (terminated)
		.reset_in14     (1'b0),                                // (terminated)
		.reset_req_in14 (1'b0),                                // (terminated)
		.reset_in15     (1'b0),                                // (terminated)
		.reset_req_in15 (1'b0)                                 // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
